version: "3.9"

services:
    backend:
        build: ./backend
        volumes:
            - ./backend/src:/USR/backend/src
        environment:
            CHOKIDAR_USEPOLLING: "true"
            PORT: ${BACKEND_PORT}
            POSTGRES_CONNECTION: ${POSTGRES_CONNECTION}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        depends_on:
            pg:
                condition: service_healthy

    pg:
        image: postgres:latest
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d Boogie"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
        volumes:
            - ./_volumes:/var/lib/postgresql/data
