version: "3.9"

services:
    database:
        build: ./database
        volumes:
            - ./database/src:/USR/database/src
        environment:
            CHOKIDAR_USEPOLLING: "true"
            PORT: ${DATABASE_PORT}
            POSTGRES_CONNECTION: ${POSTGRES_CONNECTION}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        depends_on:
            pg:
                condition: service_healthy

    frontend:
        container_name: frontend
        restart: always
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - 80:3000
        environment:
            API_PORT: ${FRONTEND_PORT}
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./frontend:/USR/src/app

    pg:
        image: postgres:latest
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d Boogie"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
        volumes:
            - ./_volumes:/var/lib/postgresql/data
